### PR TITLE
Added to Research Tree

### PR DESCRIPTION
**Pull request by nikolateslax**
Good day, developer. I hope you don't mind, but when playing with a friend using your mod, he remarked that the awesomeness provided by this mod shouldn't be available to the player immediately. I agreed with him, and decided I would go ahead and put it on the research tree.

I set it to have Advanced Electronics and Circuit Network as prerequisites - Advanced Electronics because it is rather advanced, and Circuit Network because it seems to not do much good without the circuit network. I also took the liberty of taking your microcontroller icon, and blowing it up to 128px - this way the game client doesn't scale it on its own, since that makes it look bad.

Please feel free to review my changes, and if you like them, feel free to merge them into your repository! I figured I would do the work so my friend and I could have somewhat of a more immersive version of the mod, and it would simply be rude not to offer you the fruits of my labour. Cheers!

### CODE REVIEW

**Comment by ZwerOxotnik** [comment]
First, thanks for your contribution and this detailed story.

Probably, I'll update the mod in 2 hours or later. There are some small things to fix and change. I thought about by such late technology for a while after your words... well, we'll see how players react...

**Comment by ZwerOxotnik** [comment]
Btw

https://creativecommons.org/faq/#what-can-i-do-if-i-offer-my-material-under-a-creative-commons-license-and-i-do-not-like-the-way-someone-uses-it

https://github.com/ZwerOxotnik/m-microcontroller/blob/1.0/LICENSE

**Comment by nikolateslax** [comment]
Thanks for your consideration! I recognise that perhaps depending how players react, it might be wise to add a configuration option to allow research requirement to be configurable. Honestly, the way I modified it is simply a suggestion - it could be that it should only require circuit network, or fewer packs, but only the player base will tell.

I must admit though, I'm curious why you linked the Creative Commons article and the license - I did check that I would have been inside the license terms. Was I in error?

**Comment by ZwerOxotnik** [comment]
> Was I in error?

No, well, it's tough for me to explain it. You changed code in the project under **the license and** I added your code and your "intellectual property", so it turns out this project has the intellectual property of several people regulated by CC BY 4.0 license and you have some rights/permissions (almost same as mine or literally same) due to the license and there are ways to "provide" your "influence" in this project as a licensor by a copyright... I guess...

Please note: _**I AM NOT A LAWYER.**_

> _**it might be wise to add a configuration option to allow research requirement to be configurable.**_

Yeah, and there are similar mods...

**Comment by nikolateslax** [comment]
Ah, I think I understand. I explicitly release my intellectual property and any right I may have to the code that I wrote for this project to the owner of the repository to which I submitted the pull request, and from which I forked. I do not desire, nor need, to retain any control of the code that I wrote or the image modification I created. And, in fact, I don't even need or want credit - I simply had an idea for a potential enhancement, and wanted to provide you with a working example of this. This is part of the open source ecosystem, and one that I'm glad there is.

**Pull request merged**
