### PR TITLE
Adding technologies to increase maximum progamm size and french language

### PR DESCRIPTION
**Pull request by XZ1048576**
I found the 32 instruction limit to be too restrictive. So I created technologies to increase this limit. Then I also translated the mod into French.

### CODE REVIEW

**Comment by ZwerOxotnik** [comment]
I'll add it soon.  
Please, add the localization to https://crowdin.com/translate/factorio-mods-localization/862/en-fr?filter=basic&value=0

**Comment by XZ1048576** [comment]
Great, I added localization in crowdin, but I couldn't add changes I made for english locale.

**Comment by ZwerOxotnik** [comment]
> but I couldn't add changes I made for english locale

It's fine, English localization be updated as soon I'll merge it. (Btw, I just recall, updated English localization will reset some localization on Crowdin)

**Comment by ZwerOxotnik** [comment]
Probably, I'll recheck/fix later, because I found out that `/c game.player.force.reset()` makes UI for code unreadable etc.

I'll merge it, but won't make a release temporally.

**Comment by ZwerOxotnik** [comment]
@XZ1048576, published https://mods.factorio.com/mod/m-microcontroller/downloads

**Comment by ZwerOxotnik** [comment]
@XZ1048576, b168184 (it got a reset on some lines)

https://crowdin.com/translate/factorio-mods-localization/862/en-fr?filter=basic&value=0

**Comment by XZ1048576** [comment]
@ZwerOxotnik Thanks for publishing what I did! I updated the localization on crowdin. I also update ukrainian localization of what was reseted and solved an issue with topics.comments_BIS (it was [color=жовто] instead of [color=yellow])

**Pull request merged**
